packages:
  - packages/*
  - documentation

catalog:
  "@tsconfig/node24": ^24.0.4
  "@types/jsdom": ^27.0.0
  "@types/node": ^25.0.10
  "@vitejs/plugin-vue": ^6.0.1
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.7.0
  "@vueuse/core": ^14.2.1
  consola: ^3.4.2
  eslint: ^9.39.2
  husky: ^9.1.7
  jsdom: ^28.0.0
  lint-staged: 16.2.7
  npm-run-all: ^4.1.5
  prettier: 3.8.1
  stylelint: 16.26.1
  typescript: ^5.9.3
  vite: ^7.1.11
  vite-plugin-dts: ^4.5.4
  vite-plugin-lib-inject-css: ^2.2.2
  vite-svg-loader: ^5.1.0
  vue: 3.5.22
  vue-tsc: ^3.2.5

catalogs:
  peer:
    "@vueuse/core": ~13.8.0
    vue: ~3.5.0
  storybook:
    "@storybook/addon-a11y": ^10.2.13
    "@storybook/addon-designs": ^11.1.2
    "@storybook/addon-docs": ^10.2.13
    "@storybook/addon-links": ^10.2.13
    "@storybook/addon-themes": ^10.2.13
    "@storybook/addon-vitest": 10.2.12
    "@storybook/vue3-vite": ^10.2.13
    "@storybook-community/storybook-dark-mode": ^7.1.1
    eslint-plugin-storybook: ^10.2.11
    storybook: ^10.2.13
    storybook-addon-pseudo-states: ^10.2.11
  vitest:
    "@vitest/coverage-v8": ^4.0.18
    "@vitest/ui": ^4.0.17
    vitest: ^4.0.18
