packages:
  - packages/*
  - documentation

catalog:
  "@tsconfig/node24": ^24.0.1
  "@types/jsdom": ^21.1.7
  "@types/node": ^24.2.0
  "@vitejs/plugin-vue": ^6.0.1
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.7.0
  "@vueuse/core": ^13.8.0
  consola: ^3.4.2
  eslint: 9.39.1
  husky: ^9.1.7
  jsdom: ^27.0.0
  lint-staged: 15.4.3
  npm-run-all: ^4.1.5
  prettier: 3.6.2
  stylelint: 16.25.0
  typescript: ^5.9.3
  vite: ^7.1.11
  vite-plugin-dts: ^4.5.4
  vite-plugin-lib-inject-css: ^2.2.2
  vite-svg-loader: ^5.1.0
  vue: 3.5.22
  vue-tsc: ^3.0.5

catalogs:
  peer:
    "@vueuse/core": ~13.8.0
    vue: ~3.5.0
  storybook:
    "@storybook/addon-a11y": ^10.0.8
    "@storybook/addon-designs": ^11.0.1
    "@storybook/addon-docs": ^10.0.8
    "@storybook/addon-links": ^10.0.8
    "@storybook/addon-themes": ^10.0.8
    "@storybook/vue3-vite": ^10.0.8
    "@storybook-community/storybook-dark-mode": ^7.0.2
    eslint-plugin-storybook: ^10.0.8
    storybook: ^10.0.8
  vitest:
    "@vitest/coverage-v8": ^3.2.4
    "@vitest/ui": ^3.2.4
    vitest: ^3.2.4
