packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "documentation"

catalog:
  "@tsconfig/node24": ^24.0.1
  "@types/jsdom": ^21.1.7
  "@types/node": ^24.2.0
  "@vitejs/plugin-vue": ^6.0.1
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.7.0
  "@vueuse/core": "^13.8.0"
  consola: ^3.4.2
  eslint: 9.36.0
  husky: ^9.1.7
  jsdom: ^27.0.0
  lint-staged: 15.4.3
  npm-run-all: ^4.1.5
  prettier: 3.6.2
  stylelint: 16.23.1
  typescript: ^5.9.2
  vite: ^7.1.6
  vite-plugin-dts: ^4.5.4
  vite-plugin-lib-inject-css: "^2.2.2"
  vite-svg-loader: ^5.1.0
  vue: 3.5.18
  vue-tsc: ^3.0.5

catalogs:
  # separate catalog for storybook, since most packages share the same version number
  storybook:
    storybook: ^9.1.6
    "@storybook/addon-a11y": ^9.1.6
    "@storybook/addon-docs": ^9.1.6
    "@storybook/addon-links": ^9.1.6
    "@storybook/addon-themes": ^9.1.6
    "@storybook/themes": ^9.1.6
    "@storybook/vue3-vite": ^9.1.6
    "eslint-plugin-storybook": ^9.1.6
    # version differs from main storybook version
    "@storybook/addon-designs": "^10.0.2"
    "@storybook/types": "^8.6.14"
    "storybook-dark-mode": "^4.0.2"

  # vitest and plugins which share the same version number
  vitest:
    "@vitest/coverage-v8": ^3.2.4
    "@vitest/ui": ^3.2.4
    vitest: ^3.2.4

  # peer dependencies usually define a broader version range
  peer:
    vue: ~3.5.0
    "@vueuse/core": "~13.8.0"
