packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "documentation"

catalog:
  "@tsconfig/node22": ^22.0.2
  "@types/jsdom": ^21.1.7
  "@types/node": ^22.13.4
  "@vitejs/plugin-vue": ^5.2.1
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.7.0
  consola: ^3.4.0
  eslint: 8.57.0
  husky: ^9.1.7
  jsdom: ^26.0.0
  lint-staged: 15.4.3
  npm-run-all: ^4.1.5
  prettier: 3.5.3
  rimraf: ^6.0.1
  stylelint: 16.15.0
  typescript: ^5.8.3
  vite: ^6.3.5
  vite-svg-loader: ^5.1.0
  vue: 3.5.13
  vue-tsc: ^2.2.10

catalogs:
  # separate catalog for storybook, since most packages share the same version number
  storybook:
    "@storybook/addon-a11y": ^8.6.14
    "@storybook/addon-actions": ^8.6.14
    "@storybook/addon-essentials": ^8.6.14
    "@storybook/addon-interactions": ^8.6.14
    "@storybook/addon-links": ^8.6.14
    "@storybook/addon-themes": ^8.6.14
    "@storybook/blocks": ^8.6.14
    "@storybook/manager-api": ^8.6.14
    "@storybook/test": ^8.6.14
    "@storybook/theming": ^8.6.14
    "@storybook/vue3": ^8.6.14
    "@storybook/vue3-vite": ^8.6.14
    storybook: ^8.6.14
    # version differs from main storybook version
    "@storybook/addon-designs": "^8.2.1"

  # vitest and plugins which share the same version number
  vitest:
    "@vitest/coverage-v8": ^3.1.4
    "@vitest/ui": ^3.1.4
    vitest: ^3.1.4

  # peer dependencies usually define a broader version range
  peer:
    vue: ~3.5.0
