/**
 * Semantic keyword mapping for icons. Each icon name maps to a list of
 * additional search terms so users can find icons by intent / concept
 * rather than memorising the exact file name.
 *
 * MAINTENANCE: When a new icon SVG is added to `packages/styles/src/img/icons/`,
 * it will automatically appear in the search grid (via `kdsIconNames`) and be
 * searchable by its file name. To improve discoverability, add an entry here
 * with relevant synonyms / concepts.
 */
export const keywordMap: Record<string, string[]> = {
  "add-user": ["person", "account", "new", "create", "member", "invite"],
  "ai-general": ["artificial intelligence", "machine learning", "ml", "robot"],
  "annotation-mode": ["note", "comment", "annotate", "markup"],
  "arrow-down": ["down", "navigate", "direction", "south"],
  "arrow-up": ["up", "navigate", "direction", "north"],
  "arrows-expand": ["resize", "fullscreen", "enlarge", "maximize", "grow"],
  "arrows-move": ["drag", "reorder", "reposition", "grab"],
  "arrows-order": ["sort", "reorder", "arrange", "sequence"],
  back: ["previous", "return", "left", "navigate", "history"],
  bold: ["font", "text", "weight", "strong", "typography"],
  calendar: ["date", "schedule", "event", "day", "month", "year", "picker"],
  "case-sensitive": ["uppercase", "lowercase", "letter", "match", "text"],
  "center-aligned": ["align", "text", "paragraph", "middle", "justify"],
  checkmark: ["check", "done", "complete", "success", "yes", "confirm", "tick"],
  "chevron-down": ["expand", "dropdown", "caret", "arrow", "open", "collapse"],
  "chevron-left-double": ["skip", "fast", "previous", "rewind", "navigate"],
  "chevron-left": [
    "back",
    "previous",
    "navigate",
    "caret",
    "arrow",
    "collapse",
  ],
  "chevron-right-double": ["skip", "fast", "next", "forward", "navigate"],
  "chevron-right": ["forward", "next", "navigate", "caret", "arrow", "expand"],
  "chevron-up": ["collapse", "close", "caret", "arrow", "fold"],
  "circle-error": [
    "error",
    "fail",
    "problem",
    "issue",
    "danger",
    "alert",
    "status",
  ],
  "circle-info": ["information", "help", "about", "details", "hint", "status"],
  "circle-question": [
    "help",
    "faq",
    "support",
    "ask",
    "unknown",
    "question mark",
  ],
  "circle-success": [
    "success",
    "done",
    "ok",
    "complete",
    "approved",
    "status",
    "check",
  ],
  "cloud-download": ["download", "save", "remote", "fetch", "pull"],
  "cloud-knime": ["knime", "server", "hub", "remote", "saas"],
  "cloud-pending-changes": ["sync", "unsaved", "modified", "pending", "upload"],
  "cloud-synced": ["synced", "saved", "up to date", "cloud", "remote"],
  "cloud-upload": ["upload", "push", "deploy", "publish", "send"],
  "cloud-workflow": ["remote workflow", "cloud", "server"],
  "code-block": ["code", "snippet", "programming", "script", "source"],
  "color-picker": ["color", "palette", "swatch", "pick", "eyedropper"],
  comment: ["note", "annotation", "remark", "feedback", "message"],
  component: ["module", "block", "piece", "widget", "node"],
  connection: ["link", "network", "wire", "join", "edge"],
  copy: ["duplicate", "clipboard", "clone", "paste"],
  cursor: ["pointer", "select", "mouse", "click"],
  "data-app": ["application", "dashboard", "webapp"],
  "data-value-view": ["preview", "inspect", "data", "cell"],
  "date-time": ["datetime", "timestamp", "clock", "calendar"],
  "db-database": ["database", "storage", "sql", "data"],
  "db-schema": ["schema", "structure", "model", "database"],
  "db-table-view": ["table", "view", "query", "database"],
  "db-table": ["table", "data", "rows", "columns", "database"],
  deploy: ["publish", "release", "ship", "launch", "go live"],
  detect: ["find", "discover", "scan", "identify", "magnify"],
  divider: ["separator", "line", "horizontal rule", "hr", "split"],
  duration: ["time", "interval", "period", "span", "length"],
  edit: ["modify", "change", "update", "pencil", "write"],
  education: ["learn", "school", "graduation", "hat", "teach", "tutorial"],
  "error-panel": ["error", "log", "console", "debug", "warning"],
  "execute-all": ["run all", "start all", "play all", "batch"],
  execute: ["run", "start", "play", "go", "trigger"],
  "expand-panel": ["open", "maximize", "show", "enlarge", "panel"],
  "extension-community": [
    "plugin",
    "addon",
    "community",
    "marketplace",
    "third party",
  ],
  extension: ["plugin", "addon", "module", "extra", "integration"],
  "external-link": [
    "open",
    "new tab",
    "outbound",
    "redirect",
    "navigate",
    "url",
  ],
  eye: ["view", "show", "visible", "watch", "preview", "visibility"],
  "file-export": ["export", "download", "save", "output"],
  "file-text": ["document", "text file", "page", "content"],
  file: ["document", "page", "paper", "attachment"],
  filter: ["funnel", "refine", "narrow", "sieve", "sort"],
  "flow-variable-default": ["variable", "flow", "parameter", "default"],
  "flow-variable-in-out": [
    "variable",
    "flow",
    "input",
    "output",
    "bidirectional",
  ],
  "flow-variable-in": ["variable", "flow", "input", "incoming"],
  "flow-variable-out": ["variable", "flow", "output", "outgoing"],
  "folder-plus": ["new folder", "create folder", "add folder"],
  "folder-workflow": ["workflow folder", "project", "directory"],
  folder: ["directory", "files", "organize", "group"],
  forum: ["discuss", "community", "chat", "conversation", "talk"],
  "function-catalog": ["functions", "library", "catalog", "formulas", "math"],
  home: ["house", "main", "start", "dashboard", "landing"],
  import: ["load", "bring in", "insert", "add", "ingest"],
  info: ["information", "help", "about", "details", "hint"],
  interval: ["range", "period", "between", "span"],
  italic: ["font", "text", "emphasis", "slant", "typography"],
  key: ["password", "secret", "credential", "access", "security", "lock"],
  "layout-editor": ["layout", "design", "grid", "arrange", "compose"],
  "left-aligned": ["align left", "text", "paragraph", "flush left"],
  like: ["heart", "favorite", "love", "bookmark", "star"],
  limit: ["restrict", "cap", "maximum", "constraint", "bound"],
  link: ["url", "chain", "connect", "hyperlink", "anchor"],
  "linked-metanode": ["metanode", "linked", "reference", "shared"],
  "list-bulletpoint": ["bullet", "unordered list", "ul", "items", "typography"],
  "list-number": ["ordered list", "ol", "numbered", "sequence", "typography"],
  "list-thumbs": ["thumbnails", "grid", "gallery", "images"],
  list: ["items", "menu", "rows", "lines"],
  "local-filesystem": ["local", "disk", "storage", "computer", "hard drive"],
  lock: ["secure", "private", "password", "protected", "closed"],
  metanode: ["group", "container", "sub-workflow", "wrapper"],
  "mini-map": ["overview", "navigation", "map", "zoom out", "bird's eye"],
  "minimize-dialog": ["shrink", "collapse", "hide", "reduce", "close"],
  "minimize-side-panel": [
    "sidebar",
    "collapse",
    "hide",
    "panel",
    "reduce",
    "close",
  ],
  minus: ["subtract", "remove", "decrease", "negative", "delete"],
  "more-actions": [
    "ellipsis",
    "dots",
    "menu",
    "options",
    "overflow",
    "kebab",
    "three dots",
  ],
  "node-stack": ["layers", "stack", "multiple", "batch", "group"],
  "nodes-align-horiz": ["align", "horizontal", "distribute", "arrange"],
  "nodes-align-vert": ["align", "vertical", "distribute", "arrange"],
  "open-in-new-window": [
    "external",
    "popup",
    "new tab",
    "window",
    "open",
    "launch",
  ],
  "pan-mode": ["move", "drag", "scroll", "navigate", "hand"],
  parameter: ["variable", "setting", "config", "option", "input"],
  "pending-changes": ["unsaved", "modified", "dirty", "changed", "dot"],
  placeholder: ["empty", "blank", "template", "dummy", "default"],
  plus: ["add", "create", "new", "increase", "positive"],
  quote: ["blockquote", "citation", "excerpt", "reference", "typography"],
  "re-execution": ["rerun", "retry", "repeat", "again", "redo"],
  redo: ["repeat", "forward", "again", "restore"],
  regex: ["regular expression", "pattern", "match", "search"],
  reload: ["refresh", "retry", "update", "sync", "restart"],
  rename: ["edit name", "relabel", "change name", "title"],
  replace: ["swap", "substitute", "exchange", "find and replace"],
  "reset-all": ["clear all", "revert all", "undo all", "restart"],
  "resume-execution": ["continue", "unpause", "proceed", "play"],
  "right-aligned": ["align right", "text", "paragraph", "flush right"],
  rocket: ["launch", "deploy", "fast", "boost", "speed", "start"],
  "save-as": ["save copy", "duplicate", "export", "rename save"],
  save: ["disk", "floppy", "store", "persist", "write"],
  schedule: ["cron", "timer", "clock", "automate", "recurring", "plan"],
  search: ["find", "look", "magnifying glass", "query", "lookup"],
  "secret-store": ["vault", "secrets", "credentials", "key", "secure"],
  "selected-cancel": ["cancel selection", "deselect", "abort", "stop"],
  "selected-execution": ["run selected", "execute selection", "play selected"],
  "selected-reset": ["reset selection", "clear selected", "revert"],
  send: ["submit", "deliver", "dispatch", "email", "message", "share"],
  "server-rack-workflow": ["server", "rack", "infrastructure", "hardware"],
  service: ["api", "endpoint", "server", "microservice"],
  settings: ["gear", "cog", "preferences", "configuration", "options"],
  share: ["distribute", "publish", "send", "social", "forward"],
  shortcuts: ["keyboard", "hotkey", "shortcut", "keys", "bindings"],
  "sort-ascending": ["sort", "ascending", "asc", "a-z", "smallest first"],
  "sort-descending": ["sort", "descending", "desc", "z-a", "largest first"],
  "space-local": ["local space", "workspace", "personal"],
  "space-private": ["private space", "personal", "hidden"],
  space: ["workspace", "project", "area", "hub"],
  "stepwise-execution": ["step", "debug", "one by one", "single step"],
  stop: ["halt", "cancel", "abort", "end", "terminate", "pause"],
  strikethrough: ["line through", "delete text", "crossed out", "typography"],
  team: ["group", "people", "users", "organization", "members"],
  text: ["type", "string", "content", "characters", "font"],
  textstyles: [
    "heading",
    "paragraph",
    "format",
    "styles",
    "typography",
    "font",
  ],
  "thumbs-down": ["dislike", "bad", "reject", "negative", "feedback"],
  "thumbs-up": ["like", "good", "approve", "positive", "feedback"],
  time: ["clock", "hour", "minute", "watch", "timer"],
  "to-bottom": ["scroll down", "end", "last", "bottom"],
  "to-top": ["scroll up", "beginning", "first", "top"],
  trash: ["delete", "remove", "bin", "garbage", "discard", "destroy"],
  trigger: ["event", "webhook", "automation", "fire", "signal"],
  underline: ["text decoration", "emphasis", "typography"],
  undo: ["revert", "back", "cancel", "restore", "previous"],
  unlink: ["disconnect", "break link", "detach", "remove link"],
  user: ["person", "account", "profile", "avatar", "member"],
  version: ["history", "revision", "changelog", "branch", "git"],
  "view-cards": ["grid view", "tiles", "gallery", "cards"],
  warning: ["caution", "alert", "attention", "exclamation", "notice", "status"],
  workflow: ["process", "pipeline", "flow", "diagram", "graph"],
  "x-close": ["close", "dismiss", "remove", "cancel", "exit", "cross"],
};
