/* eslint-disable max-lines */
import type { KdsDateTimeFormatEntry } from "../types";

export const dateFormats: KdsDateTimeFormatEntry[] = [
  {
    format: "yyyy-MM-dd",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-02-04",
  },
  {
    format: "yyyy-MM",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-02",
  },
  {
    format: "yyyyMMdd",
    temporalType: "DATE",
    category: "STANDARD",
    example: "20260204",
  },
  {
    format: "YYYY-MM",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-02",
  },
  {
    format: "yyyy-M-d",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-2-4",
  },
  {
    format: "yyyy-MMMM-dd",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-Februar-04",
  },
  {
    format: "yyyy-MMM-dd",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-Feb.-04",
  },
  {
    format: "yyyy-ww",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-06",
  },
  {
    format: "yyyy-D",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-35",
  },
  {
    format: "YYYYwwee",
    temporalType: "DATE",
    category: "STANDARD",
    example: "20260603",
  },
  {
    format: "yyyy-QQ",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-01",
  },
  {
    format: "yyyy-QQQ",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-Q1",
  },
  {
    format: "yyyy-'W'ww",
    temporalType: "DATE",
    category: "STANDARD",
    example: "2026-W06",
  },
  {
    format: "dd/MM/yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "04/02/2026",
  },
  {
    format: "dd.MM.yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "04.02.2026",
  },
  {
    format: "dd/MM/yy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "04/02/26",
  },
  {
    format: "dd.MM.yy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "04.02.26",
  },
  {
    format: "d. MMMM yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "4. Februar 2026",
  },
  {
    format: "dd MMM yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "04 Feb. 2026",
  },
  {
    format: "d. MMMM YYYY",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "4. Februar 2026",
  },
  {
    format: "d/M/yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "4/2/2026",
  },
  {
    format: "dd MMMM yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "04 Februar 2026",
  },
  {
    format: "yyyy/MM/dd",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "2026/02/04",
  },
  {
    format: "yyyy.MM.dd",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "2026.02.04",
  },
  {
    format: "yyyy-MM-dd",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "2026-02-04",
  },
  {
    format: "MMM yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "Feb. 2026",
  },
  {
    format: "MMMM yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "Februar 2026",
  },
  {
    format: "dd/M/yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "04/2/2026",
  },
  {
    format: "MM-yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "02-2026",
  },
  {
    format: "Q/yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "1/2026",
  },
  {
    format: "MMM. yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "Feb.. 2026",
  },
  {
    format: "d-MMM-yy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "4-Feb.-26",
  },
  {
    format: "d.M.yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "4.2.2026",
  },
  {
    format: "d/MM/yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "4/02/2026",
  },
  {
    format: "d. MMM. yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "4. Feb.. 2026",
  },
  {
    format: "yyyy MMM dd",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "2026 Feb. 04",
  },
  {
    format: "QQQ/yyyy",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "Q1/2026",
  },
  {
    format: "yyyy/QQQ",
    temporalType: "DATE",
    category: "EUROPEAN",
    example: "2026/Q1",
  },
  {
    format: "MM/dd/yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "02/04/2026",
  },
  {
    format: "MM/dd/yy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "02/04/26",
  },
  {
    format: "MMM d, yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "Feb. 4, 2026",
  },
  {
    format: "MMMM yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "Februar 2026",
  },
  {
    format: "MM/yy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "02/26",
  },
  {
    format: "MM/dd/YYYY",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "02/04/2026",
  },
  {
    format: "yyyy/MM/dd",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "2026/02/04",
  },
  {
    format: "yyyy-MM-dd",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "2026-02-04",
  },
  {
    format: "yyyyMMdd",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "20260204",
  },
  {
    format: "M/d/yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "2/4/2026",
  },
  {
    format: "M/d/yy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "2/4/26",
  },
  {
    format: "MM-dd-yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "02-04-2026",
  },
  {
    format: "MMM. yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "Feb.. 2026",
  },
  {
    format: "MMM yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "Feb. 2026",
  },
  {
    format: "MM/yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "02/2026",
  },
  {
    format: "MMM dd, yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "Feb. 04, 2026",
  },
  {
    format: "Q/yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "1/2026",
  },
  {
    format: "QQ/yyyy",
    temporalType: "DATE",
    category: "AMERICAN",
    example: "01/2026",
  },

  {
    format: "yyyy-MM-dd HH:mm",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04 09:02",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04 09:02:48",
  },
  {
    format: "yyyy-MM-dd;HH:mm",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04;09:02",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss.S",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04 09:02:48.2",
  },
  {
    format: "yyyy-MM-dd;HH:mm:ss.S",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04;09:02:48.2",
  },
  {
    format: "yyyy-MM-dd;HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04;09:02:48",
  },
  {
    format: "yyyy-MM-dd HH:mm[:ss[.SSS]]",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04 09:02:48.213",
  },
  {
    format: "yyyy-MM-dd HH:mm[:ss]",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04 09:02:48",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss[.SSS]",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm[:ss[.SSS]]",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm[:ss]",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48",
  },
  {
    format: "yyyy-MMM-dd HH:mm",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-Feb.-04 09:02",
  },
  {
    format: "yyyy-MMM-dd HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-Feb.-04 09:02:48",
  },
  {
    format: "yyyy-MMM-dd'T'HH:mm",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-Feb.-04T09:02",
  },
  {
    format: "yyyy-MMM-dd'T'HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-Feb.-04T09:02:48",
  },
  {
    format: "yyyy-MMM-dd;HH:mm",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-Feb.-04;09:02",
  },
  {
    format: "yyyy-MMM-dd;HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "STANDARD",
    example: "2026-Feb.-04;09:02:48",
  },
  {
    format: "yyyy-MM-dd HH:mm",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04 09:02",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04 09:02:48",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss.SSS",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04 09:02:48.213",
  },
  {
    format: "yyyy-MMM-dd HH:mm",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-Feb.-04 09:02",
  },
  {
    format: "yyyy-MMM-dd HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-Feb.-04 09:02:48",
  },
  {
    format: "yyyy-MMM-dd'T'HH:mm",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-Feb.-04T09:02",
  },
  {
    format: "yyyy-MMM-dd'T'HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-Feb.-04T09:02:48",
  },
  {
    format: "yyyy-MMM-dd;HH:mm",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-Feb.-04;09:02",
  },
  {
    format: "yyyy-MMM-dd;HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-Feb.-04;09:02:48",
  },
  {
    format: "dd/MM/yyyy HH:mm",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04/02/2026 09:02",
  },
  {
    format: "dd/MM/yyyy HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04/02/2026 09:02:48",
  },
  {
    format: "dd/MM/yyyy hh:mm a",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04/02/2026 09:02 AM",
  },
  {
    format: "dd.MM.yyyy HH:mm",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04.02.2026 09:02",
  },
  {
    format: "dd.MM.yyyy HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04.02.2026 09:02:48",
  },
  {
    format: "dd.MM.yyyy hh:mm a",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04.02.2026 09:02 AM",
  },
  {
    format: "dd MMM yyyy HH:mm ",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04 Feb. 2026 09:02 ",
  },
  {
    format: "dd MMM yyyy HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "04 Feb. 2026 09:02:48",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48",
  },
  {
    format: "MM/dd/yyyy HH:mm",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "02/04/2026 09:02",
  },
  {
    format: "MM/dd/yyyy HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "02/04/2026 09:02:48",
  },
  {
    format: "MM/dd/yyyy HH:mm:ss.SSS",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "02/04/2026 09:02:48.213",
  },
  {
    format: "yyyy-MM-dd HH:mm",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04 09:02",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04 09:02:48",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss.SSS",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04 09:02:48.213",
  },
  {
    format: "MM/dd/yyyy h:mm a",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "02/04/2026 9:02 AM",
  },
  {
    format: "M/d/yyyy h:mm:ss a",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "2/4/2026 9:02:48 AM",
  },
  {
    format: "MM/dd/yyyy h:mm:ss a",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "02/04/2026 9:02:48 AM",
  },
  {
    format: "yyyyMMdd HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "20260204 09:02:48",
  },
  {
    format: "yyyyMMdd HH:mm",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "20260204 09:02",
  },
  {
    format: "MMM dd, yyyy h:mm a",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "Feb. 04, 2026 9:02 AM",
  },
  {
    format: "MMM dd, yyyy HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "Feb. 04, 2026 09:02:48",
  },
  {
    format: "MMM dd, yyyy HH:mm",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "Feb. 04, 2026 09:02",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm",
    temporalType: "DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02",
  },

  {
    format: "HH:mm",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02",
  },
  {
    format: "HH:mm:ss",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02:48",
  },
  {
    format: "H:mm",
    temporalType: "TIME",
    category: "STANDARD",
    example: "9:02",
  },
  {
    format: "H:mm:ss",
    temporalType: "TIME",
    category: "STANDARD",
    example: "9:02:48",
  },
  {
    format: "HH:mm:ss.SSS",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02:48.213",
  },
  {
    format: "HH:mm:ss[.SSS]",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02:48.213",
  },
  {
    format: "HH:mm:ss.nnn",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02:48.213071454",
  },
  {
    format: "HH:mm:ss[.n]",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02:48.213071454",
  },
  {
    format: "HH:mm[:ss[.SSS]]",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02:48.213",
  },
  {
    format: "hh:mma",
    temporalType: "TIME",
    category: "STANDARD",
    example: "09:02AM",
  },
  {
    format: "h:mm a",
    temporalType: "TIME",
    category: "STANDARD",
    example: "9:02 AM",
  },
  {
    format: "h:mm:ss a",
    temporalType: "TIME",
    category: "STANDARD",
    example: "9:02:48 AM",
  },
  {
    format: "HH:mm",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02",
  },
  {
    format: "HH:mm:ss",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02:48",
  },
  {
    format: "H:mm",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "9:02",
  },
  {
    format: "H:mm:ss",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "9:02:48",
  },
  {
    format: "HH:mm:ss.SSS",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02:48.213",
  },
  {
    format: "HH:mm:ss[.SSS]",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02:48.213",
  },
  {
    format: "HH:mm:ss.nnn",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02:48.213071454",
  },
  {
    format: "HH:mm:ss[.n]",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02:48.213071454",
  },
  {
    format: "HH:mm[:ss[.SSS]]",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02:48.213",
  },
  {
    format: "hh:mma",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "09:02AM",
  },
  {
    format: "h:mm a",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "9:02 AM",
  },
  {
    format: "h:mm:ss a",
    temporalType: "TIME",
    category: "EUROPEAN",
    example: "9:02:48 AM",
  },
  {
    format: "HH:mm",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02",
  },
  {
    format: "HH:mm:ss",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02:48",
  },
  {
    format: "H:mm",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "9:02",
  },
  {
    format: "H:mm:ss",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "9:02:48",
  },
  {
    format: "HH:mm:ss.SSS",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02:48.213",
  },
  {
    format: "HH:mm:ss[.SSS]",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02:48.213",
  },
  {
    format: "HH:mm:ss.nnn",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02:48.213071454",
  },
  {
    format: "HH:mm:ss[.n]",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02:48.213071454",
  },
  {
    format: "HH:mm[:ss[.SSS]]",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02:48.213",
  },
  {
    format: "hh:mma",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "09:02AM",
  },
  {
    format: "h:mm a",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "9:02 AM",
  },
  {
    format: "h:mm:ss a",
    temporalType: "TIME",
    category: "AMERICAN",
    example: "9:02:48 AM",
  },

  {
    format: "yyyy-MM-dd'T'HH:mm:ss'Z'",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48Z",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSVV",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213+0100",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS[Z]",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213+0100",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ssXXX",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss'['VV']'",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48[Europe/Berlin]",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS[ZZZZ]",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48.213GMT+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSVV'['zzzz']'",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example:
      "2026-02-04T09:02:48.213Europe/Berlin[Mitteleuropäische Normalzeit]",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ssVV",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04T09:02:48Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss VV",
    temporalType: "ZONED_DATE_TIME",
    category: "STANDARD",
    example: "2026-02-04 09:02:48 Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss'Z'",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48Z",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48.213+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSVV",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48.213Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48.213+0100",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS[Z]",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48.213+0100",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ssXXX",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss'['VV']'",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48[Europe/Berlin]",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS[ZZZZ]",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48.213GMT+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSVV'['zzzz']'",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example:
      "2026-02-04T09:02:48.213Europe/Berlin[Mitteleuropäische Normalzeit]",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ssVV",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04T09:02:48Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss VV",
    temporalType: "ZONED_DATE_TIME",
    category: "EUROPEAN",
    example: "2026-02-04 09:02:48 Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss'Z'",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48Z",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48.213+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSVV",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48.213Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48.213+0100",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS[Z]",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48.213+0100",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss'['VV']'",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48[Europe/Berlin]",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS[ZZZZ]",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48.213GMT+01:00",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSSVV'['zzzz']'",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example:
      "2026-02-04T09:02:48.213Europe/Berlin[Mitteleuropäische Normalzeit]",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ssVV",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd HH:mm:ss VV",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04 09:02:48 Europe/Berlin",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48.213",
  },
  {
    format: "yyyy-MM-dd'T'HH:mm:ssXXX",
    temporalType: "ZONED_DATE_TIME",
    category: "AMERICAN",
    example: "2026-02-04T09:02:48+01:00",
  },
];
