<script setup lang="ts">
import { computed, onMounted, ref, toRef, useId, watch } from "vue";
import { useElementSize } from "@vueuse/core";

import KdsIcon from "../accessories/Icon/KdsIcon.vue";

import type { KdsTab, KdsTabBarProps } from "./types";
import { useTabBarIconHiding } from "./useTabBarIconHiding";

const props = withDefaults(defineProps<KdsTabBarProps>(), {
  size: "small",
  fullWidth: false,
  disabled: false,
});

const modelValue = defineModel<string | number>({ required: false });

const emit = defineEmits<{
  tabClick: [tab: KdsTab];
}>();

const autoGeneratedName = useId();
const inputName = computed(() => props.name ?? autoGeneratedName);

// Local model value to handle SSR hydration issues
const localModelValue = ref(modelValue.value);

watch(
  () => modelValue.value,
  (newValue) => {
    localModelValue.value = newValue;
  },
);

watch(localModelValue, (newValue) => {
  if (modelValue.value !== newValue) {
    modelValue.value = newValue;
  }
});

const handleChange = (tab: KdsTab) => {
  if (!tab.disabled && !props.disabled) {
    emit("tabClick", tab);
  }
};

const availableWidthContainer = ref<HTMLElement | null>(null);
const { width } = useElementSize(availableWidthContainer);
const { shouldHideIcons, setItemEl } = useTabBarIconHiding({
  width,
  tabs: toRef(props, "tabs"),
  containerEl: availableWidthContainer,
});

const isSelected = (tab: KdsTab) => localModelValue.value === tab.value;
const isTabDisabled = (tab: KdsTab) => props.disabled || tab.disabled;

const tabBarClass = computed(() => ({
  "tab-bar": true,
  [props.size]: true,
  "full-width": props.fullWidth,
}));

// Auto-select first available tab if none is selected
onMounted(() => {
  const availableTabs = props.tabs.filter((tab) => !isTabDisabled(tab));
  let initialTab = availableTabs.find(
    (tab) => tab.value === localModelValue.value,
  );

  if (!initialTab) {
    initialTab = availableTabs[0];
    if (initialTab) {
      localModelValue.value = initialTab.value;
      modelValue.value = initialTab.value;
    }
  }
});
</script>

<template>
  <div ref="availableWidthContainer" :class="tabBarClass" role="tablist">
    <label
      v-for="tab in tabs"
      :key="tab.value"
      :ref="(el) => setItemEl(tab.value, el)"
      :title="tab.title ?? tab.label"
      :class="{
        'tab-wrapper': true,
        selected: isSelected(tab),
        disabled: isTabDisabled(tab),
      }"
    >
      <input
        v-model="localModelValue"
        :name="inputName"
        :value="tab.value"
        :disabled="isTabDisabled(tab)"
        type="radio"
        role="tab"
        :aria-selected="isSelected(tab)"
        @change="handleChange(tab)"
      />
      <span class="tab">
        <KdsIcon
          v-if="tab.icon && !shouldHideIcons"
          :name="tab.icon"
          :class="`icon-${size}`"
        />
        <span class="label">{{ tab.label }}</span>
        <span v-if="isSelected(tab)" class="indicator" />
      </span>
    </label>
  </div>
</template>

<style scoped>
.tab-bar {
  display: flex;
  flex-wrap: nowrap;
  overflow: auto visible;
  scrollbar-width: none;
  -ms-overflow-style: none;
  border-bottom: var(--kds-border-base-subtle);
  border-bottom-width: var(--kds-core-border-width-m);
}

.tab-bar::-webkit-scrollbar {
  display: none;
}

.tab-wrapper {
  position: relative;
  min-width: 0;
}

.tab-bar:not(.full-width) .tab-wrapper {
  flex: 0 1 auto;
  min-width: var(--kds-dimension-component-width-4x);
}

.tab-wrapper input[type="radio"] {
  position: absolute;
  width: 0;
  height: 0;
  pointer-events: none;
  opacity: 0;
}

.label {
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  font: var(--kds-font-base-interactive-medium-strong);
  color: var(--kds-color-text-and-icon-neutral);
  white-space: nowrap;
}

.tab {
  position: relative;
  display: flex;
  align-items: center;
  min-width: 0;
  cursor: pointer;
  background: var(--kds-color-background-neutral-initial);
  border-bottom: var(--kds-border-action-transparent);
  border-bottom-width: var(--kds-core-border-width-m);
  border-radius: var(--kds-border-radius-container-none);
  transition: all 0.2s;
}

.tab :is(.icon-small, .icon-large) {
  flex-shrink: 0;
}

.tab-bar.small .tab {
  gap: var(--kds-spacing-container-0-37x);
  height: var(--kds-dimension-component-height-1-75x);
  padding: 0
    calc(var(--kds-spacing-container-0-5x) - var(--kds-core-border-width-m));
}

.tab-bar.large .tab {
  gap: var(--kds-spacing-container-0-5x);
  height: var(--kds-dimension-component-height-2-25x);
  padding: 0
    calc(var(--kds-spacing-container-0-75x) - var(--kds-core-border-width-m));
}

.tab-bar.large .label {
  font: var(--kds-font-base-interactive-large-strong);
}

.tab-wrapper.disabled {
  cursor: not-allowed;

  .tab {
    cursor: not-allowed;
    opacity: 0.5;
  }
}

.tab-wrapper.selected .tab {
  border-bottom-color: var(--kds-color-border-selected-bold);

  .label {
    color: var(--kds-color-text-and-icon-selected);
  }
}

.tab-bar.full-width .tab-wrapper {
  flex: 1;
}

.tab-bar.full-width .tab {
  justify-content: center;
  width: 100%;
}

.tab-wrapper input:focus-visible + .tab {
  outline: var(--kds-border-action-focused);
  outline-offset: var(--kds-spacing-offset-focus);
}

.tab-wrapper:hover:not(.disabled, .selected) .tab {
  background: var(--kds-color-background-neutral-hover);
}

.tab-wrapper:active:not(.disabled, .selected) .tab {
  background: var(--kds-color-background-neutral-active);
}

.tab-wrapper.selected .tab .indicator {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  height: var(--kds-core-border-width-m);
  background: var(--kds-color-background-selected-bold-initial);
  border: var(--kds-border-action-selected);
  border-top-left-radius: var(--kds-border-radius-container-0-12x);
  border-top-right-radius: var(--kds-border-radius-container-0-12x);
}

.tab-bar.large .tab-wrapper.selected .tab .label {
  font: var(--kds-font-base-title-large);
}

/* Small size icons */
.tab-bar.small .icon-small {
  width: var(--kds-dimension-component-width-1x);
  height: var(--kds-dimension-component-height-1x);
}

.tab-bar.small .tab-wrapper.selected .icon-small {
  color: var(--kds-color-text-and-icon-selected);
}

/* Large size icons */
.tab-bar.large .icon-large {
  width: var(--kds-dimension-component-width-1-25x);
  height: var(--kds-dimension-component-height-1-25x);
}

.tab-bar.large .tab-wrapper.selected .icon-large {
  color: var(--kds-color-text-and-icon-selected);
}
</style>
